server:
  port: 8080

redis:
  addr: "redis:6379"
  password: ""
  db: 0
  pool_size: 500
  min_idle_conns: 50

postgres:
  host: "db"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "testing"
  sslmode: "disable"

clickhouse:
  addr:
    - "clickhouse:9000"
  database: "default"
  username: "testing"
  password: "testing"
